{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tutorial\n",
    "\n",
    "> TODO"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# all_slow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%reload_ext autoreload\n",
    "%autoreload 2\n",
    "from fastai2.vision.all import *\n",
    "from fastexplorer.all import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "path = untar_data(URLs.MNIST_TINY)\n",
    "dls = ImageDataLoaders.from_folder(path)\n",
    "learn = cnn_learner(dls, resnet18, pretrained=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "m = learn.model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Started server process [22762]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n",
      "INFO:     ('127.0.0.1', 35316) - \"WebSocket /ws\" [accepted]\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 47, in endpoint\n",
      "    msg = await websocket.receive_json()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 98, in receive_json\n",
      "    self._raise_on_disconnect(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 80, in _raise_on_disconnect\n",
      "    raise WebSocketDisconnect(message[\"code\"])\n",
      "starlette.websockets.WebSocketDisconnect: 1001\n",
      "INFO:     ('127.0.0.1', 35434) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 56, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 63, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 35464) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 56, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 63, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 35576) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 56, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 63, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     ('127.0.0.1', 35740) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 56, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 63, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     ('127.0.0.1', 35822) - \"WebSocket /ws\" [accepted]\n",
      "INFO:     Client connected: {'client': 'web_client'}\n",
      "INFO:     Client msg: {'event': 'load_input'}\n",
      "INFO:     Invalid event: load_input\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 153, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py\", line 45, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/middleware/errors.py\", line 146, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 56, in endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"/home/renato/github/fastexplorer/fastexplorer/explorer.py\", line 63, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 137, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 211, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 555, in send\n",
      "    await self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml2/lib/python3.8/site-packages/websockets/protocol.py\", line 803, in ensure_open\n",
      "    raise self.connection_closed_exc()\n",
      "websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), no reason\n",
      "INFO:     Shutting down\n",
      "INFO:     Waiting for application shutdown.\n",
      "INFO:     Application shutdown complete.\n",
      "INFO:     Finished server process [22762]\n"
     ]
    }
   ],
   "source": [
    "learn.fastexplorer(True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# TODO"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ml2",
   "language": "python",
   "name": "ml2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
